spring.application.name=stock-backend

# Disable Spring Boot's default database auto-configuration
spring.datasource.url= #
spring.datasource.driver-class-name= # 
spring.jpa.database-platform= # 

# Prevent Hibernate from trying to connect to a database
spring.jpa.hibernate.ddl-auto=none